In [22]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from shapely.geometry import Point, Polygon, LineString

In [23]:
# 공간 데이터 파일 읽기  
gdf = gpd.read_file("emd.shp", encoding='cp949').to_crs('EPSG:4166')

In [24]:
aed_data = pd.read_csv("../data/AED.csv")

In [29]:
aed_geo = gpd.GeoDataFrame(
    aed_data, geometry=gpd.points_from_xy(aed_data['경도'], aed_data['위도']), crs="EPSG:4166"
)

In [30]:
gdf

,EMD_CD,EMD_ENG_NM,EMD_KOR_NM,geometry
0,11110101,Cheongun-dong,청운동,"POLYGON ((126.97556 37.58968, 126.97549 37.589..."
1,11110102,Singyo-dong,신교동,"POLYGON ((126.97031 37.58418, 126.97033 37.584..."
2,11110103,Gungjeong-dong,궁정동,"POLYGON ((126.974 37.58654, 126.97401 37.58653..."
3,11110104,Hyoja-dong,효자동,"POLYGON ((126.97356 37.58323, 126.97355 37.582..."
4,11110105,Changseong-dong,창성동,"POLYGON ((126.97353 37.58182, 126.97354 37.581..."
...,...,...,...,...
5061,52800380,Baeksan-myeon,백산면,"POLYGON ((126.77572 35.72071, 126.77578 35.720..."
5062,52800390,Sangseo-myeon,상서면,"POLYGON ((126.67119 35.65883, 126.67125 35.658..."
5063,52800400,Haseo-myeon,하서면,"POLYGON ((126.66959 35.73881, 126.67028 35.737..."
5064,52800410,Julpo-myeon,줄포면,"POLYGON ((126.72208 35.62205, 126.72208 35.621..."
5065,52800420,Wido-myeon,위도면,"MULTIPOLYGON (((126.28921 35.62538, 126.28921 ..."

In [31]:
aed_geo

,AED모델명,우편번호(앞자리),우편번호(뒤자리),관리책임자명,관리자연락처,설치기관주소,설치기관전화번호,설치위치,제조사,설치기관명,경도,위도,geometry
0,HeartOn A16-GS,17,4,전용선,02-951-1619,"서울특별시 노원구 노원로28길 15 (상계동, 상계1차중앙하이츠아파트)",02-951-1619,101동 경비실,메디아나,중앙하이츠1차아파트,127.068914,37.653727,POINT (127.06891 37.65373)
1,HR-501,70,61,조용성,02-870-2662,"서울특별시 동작구 보라매로5길 20, 서울특별시보라매병원 (신대방동)",02-870-2096,희망관 1층 안내데스크,라디안큐바이오,서울특별시보라매병원,126.924332,37.493014,POINT (126.92433 37.49301)
2,HR-501,70,61,조용성,02-870-2662,"서울특별시 동작구 보라매로5길 20, 서울특별시보라매병원 (신대방동)",02-870-2096,희망관 지하1층 경전철 지하연결통로,라디안큐바이오,서울특별시보라매병원,126.924332,37.493014,POINT (126.92433 37.49301)
3,HeartOn A16-GS,18,27,손광윤,02-973-3433,"서울특별시 노원구 노원로1길 21 (공릉동, 공릉9단지청솔아파트)",029733433,관리사무소 입구,메디아나,청솔9단지아파트,127.085159,37.621436,POINT (127.08516 37.62144)
4,HeartOn A16-GS,18,27,손광윤,02-973-3433,"서울특별시 노원구 노원로1길 21 (공릉동, 공릉9단지청솔아파트)",029733433,관리사무소 내부,메디아나,청솔9단지아파트,127.085170,37.621450,POINT (127.08517 37.62145)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,HeartOn A16-GS,28,76,보건교사,745-8110,"서울특별시 성북구 삼선교로16길 118, 한성여자중학교 (삼선동2가)",02-745-8110,보건실 옆,(주)메디아나,한성여자중학교,127.011313,37.582000,POINT (127.01131 37.582)
9996,HeartOn A16-GS,20,40,송수연,02-973-5012,서울특별시 중랑구 공릉로2길 60-25 (묵동),02-973-5012,1층 현관 엘리베이터 옆,(주)메디아나,태릉중학교,127.083436,37.612532,POINT (127.08344 37.61253)
9997,HeartOn A16-GS,28,59,권혜진,010-4499-8769,"서울특별시 성북구 보문로 50, 동인빌딩 (보문동7가)",02-927-6060,6층 병실,(주)메디아나,케어윌,127.022673,37.579923,POINT (127.02267 37.57992)
9998,Heart On A16-GS,77,40,황정운,02-2061-3233,"서울특별시 강서구 곰달래로57가길 26, 화곡청소년센터 (화곡동)",02-2061-3234,1층 안내데스크,메디아나,화곡청소년센터,126.860749,37.534802,POINT (126.86075 37.5348)
9999,Heart On A16-GS,75,7,손예진,070-4329-0283,"서울특별시 강서구 양천로11길 47, 한서고등학교 (방화동)",070-4329-0283,본관1층 서쪽입구,메디아나,한서고등학교,126.808144,37.574793,POINT (126.80814 37.57479)

In [32]:
df = gpd.sjoin(aed_geo, gdf)

ValueError: 'left_df' should be GeoDataFrame, got <class 'pandas.core.frame.DataFrame'>